spring:
  application:
    name: api-gateway


server:
  port: 8085

services:
  patient-service:
    url: http://localhost:8081/patients
  praticien-service:
    url: http://localhost:8082/praticiens
  rendez-vous-service:
    url:  http://localhost:8083/rendez-vous
  dossier-medical-service:
    url: http://localhost:8084/dossier-medicaux

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

config:
  activate:
    on-profile: docker

---
spring.config.activate.on-profile: docker

services:
  patient-service:
    url: http://host.docker.internal:8081/patients
  praticien-service:
    url: http://host.docker.internal:8082/praticiens
  rendez-vous-service:
    url:  http://host.docker.internal:8083/rendez-vous
  dossier-medical-service:
    url: http://host.docker.internal:8084/dossier-medicaux


eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/