spring:
  application:
    name: dossier-medical

server:
  port: 8084

services:
  patient-service:
    url: http://localhost:8081/patients/{patientId}
  praticien-service:
    url: http://localhost:8082/praticiens/{praticienId}


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # URL du serveur Eureka
    registerWithEureka: true      # S'enregistre auprès d'Eureka
    fetchRegistry: true           # Récupère le registre
  instance:
    preferIpAddress: true

config:
  activate:
    on-profile: docker

---
spring.config.activate.on-profile: docker

services:
  patient-service:
    url: http://host.docker.internal:8081/patients/{patientId}
  praticien-service:
    url: http://host.docker.internal:8082/praticiens/{praticienId}

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/


